# **Aim: Implement Naive Bayes classifier : Weather Example**

In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild', 'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes', 'Yes','Yes','Yes','Yes','No']

#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)



Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [2]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [3]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [4]:
#Create a Classifier
model=MultinomialNB()

# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [5]:
#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [6]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


In [7]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


# **2_NB_Classifier_Iris_2Classes**

In [8]:
#Import scikit-learn dataset library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

# print the names of the 13 features
print("Features: ", iris.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)

# print data(feature)shape
print("\nData shape: ",iris.data.shape)

#print data(target)shape
print("\nTraget shape: ",iris.target.shape)

#print("\nData: ",iris.data)
#print("\nTarget: ",iris.target)

print("\nData type: ",type(iris.data))

newdata = iris.data[50:,:]
newtarget = iris.target[50:]

# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)

#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Traget shape:  (150,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (100, 4)

New Traget shape:  (100,)


In [9]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata, newtarget, test_size = 0.30, random_state = 5)

In [10]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))


Accuracy: 0.9


In [11]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [12]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


# **Task 1:**
Try the algo on Dataset2 - OneHotEncoding of features:
and Train test Division 75%-25%

In [13]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [14]:
from google.colab import drive
drive.mount('/content/drive')
datasets = pd.read_csv('/content/drive/MyDrive/CE Sem 6/ML/data/Dataset2.csv')
print("\nData :\n",datasets)

X = datasets.iloc[:, :-1].values

# Only last column, 0 for 1st column and -1 for last colum,-2 for 2nd last column
Y = datasets.iloc[:, -1].values
print("\n\nInput : \n", X)
print("\n\nOutput: \n", Y)

Mounted at /content/drive

Data :
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


Input : 
 [['R' 'H' 'F' 'Normal']
 ['R' 'H' 'T' 'High']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'T' 'Low']
 ['O' 'C' 'T' 'Normal']
 ['R' 'C' 'F' 'Normal']
 ['R' 'C' 'F' 'Low']
 ['S' 'M' 'F' 'High']
 ['R' 'M' 'T' 'High']
 ['O' 'M' 'T' 'Low']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'T' 'Normal']]


Output: 
 ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [15]:
le = LabelEncoder()

datasets1 = pd.read_csv('/content/drive/MyDrive/CE Sem 6/ML/data/Dataset2.csv')
dummy = pd.get_dummies(datasets1['Outlook'])
X[ : ,0] = le.fit_transform(X[ : ,0])

# print("\n\nDummy :\n",dummy) 

datasets1 = datasets1.drop(['Outlook','Class'],axis=1)
datasets1 = pd.concat([dummy,datasets1],axis=1)


X[ : ,1] = le.fit_transform(X[ : ,1])
dummy = pd.get_dummies(datasets1['Temp'])
datasets1 = datasets1.drop(['Temp'],axis=1)
datasets1 = pd.concat([dummy,datasets1],axis=1)


X[ : ,2] = le.fit_transform(X[ : ,2])
dummy = pd.get_dummies(datasets1['Wind'])
datasets1 = datasets1.drop(['Wind'],axis=1)
datasets1 = pd.concat([dummy,datasets1],axis=1)


X[ : ,3] = le.fit_transform(X[ : ,3])
dummy = pd.get_dummies(datasets1['Humidity'])
datasets1 = datasets1.drop(['Humidity'],axis=1)
datasets1 = pd.concat([dummy,datasets1],axis=1)


print("\n\nFinal Data :\n",datasets1)
# print("\n\nInput : \n", X)



Final Data :
     High  Low  Normal  F  T  C  H  M  O  R  S
0      0    0       1  1  0  0  1  0  0  1  0
1      1    0       0  0  1  0  1  0  0  1  0
2      0    0       1  1  0  0  1  0  1  0  0
3      0    0       1  1  0  0  0  1  0  0  1
4      0    0       1  1  0  0  0  1  0  0  1
5      0    1       0  0  1  0  0  1  0  0  1
6      0    0       1  0  1  1  0  0  1  0  0
7      0    0       1  1  0  1  0  0  0  1  0
8      0    1       0  1  0  1  0  0  0  1  0
9      1    0       0  1  0  0  0  1  0  0  1
10     1    0       0  0  1  0  0  1  0  1  0
11     0    1       0  0  1  0  0  1  1  0  0
12     0    0       1  1  0  0  1  0  1  0  0
13     0    0       1  0  1  0  0  1  0  0  1


In [16]:
# Y[0] = le.fit_transform(Y[0]) 
#Use One Hot Encoder from scikit learn
# onehotencoder = OneHotEncoder()
# Y = onehotencoder.fit_transform(Y.reshape(-1,1)).toarray()
print(Y)
datasets2 = pd.read_csv('/content/drive/MyDrive/CE Sem 6/ML/data/Dataset2.csv')
dummy = pd.get_dummies(datasets2['Class'])
datasets2 = datasets2.drop(['Class', 'Wind', 'Outlook', 'Temp', 'Humidity'], axis=1)
datasets2 = pd.concat([dummy,datasets2],axis=1)

print(datasets2)


['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']
    N  Y
0   1  0
1   1  0
2   0  1
3   1  0
4   0  1
5   0  1
6   0  1
7   0  1
8   0  1
9   0  1
10  0  1
11  0  1
12  0  1
13  1  0


In [17]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(datasets1, Y, 
                                                                    test_size = 0.25, random_state = 97)

In [18]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [19]:
# from sklearn import metrics
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:" ,metrics.accuracy_score(target_test, target_pred))

from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.5
precision: [0.  0.5]
recall: [0. 1.]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
# 3.1 Questions: For Task - 1

# (1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
# mal’, and Wind = ’False’?
test1 = pd.DataFrame({'High': [0], 'Low': [0], 'Normal': [1],
                        'F': [1], 'T': [0],
                        'C': [0],'H': [0], 'M': [1],
                        'O': [0], 'R': [1], 'S': [0],})
y_pred = gnb.predict(test1)
print(y_pred)

['Y']


In [21]:
# (2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
# and Wind = ’True’?

test2 = pd.DataFrame({'High': [1], 'Low': [0], 'Normal': [0],
                        'F': [0], 'T': [1],
                        'C': [1],'H': [0], 'M': [0],
                        'O': [0], 'R': [0], 'S': [1],})
y_pred = gnb.predict(test2)
print(y_pred)

['Y']


In [22]:
# (4) For question 1 and 2 mention the probability estimates of the trained model.
print("test 1: ",gnb.predict_proba(test1))

print("test 2: ",gnb.predict_proba(test2))

test 1:  [[0. 1.]]
test 2:  [[0. 1.]]


# **Task 2:**
Apply algorithm on wine dataset - LabelEncoding of
features: and Train test Division 80%-20%

In [23]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn import datasets

wine_dataset = datasets.load_wine()

# print the names of the 13 features
print("Features: ", wine_dataset.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine_dataset.target_names)

df_wine = pd.DataFrame(wine_dataset.data, columns=wine_dataset.feature_names)
df_wine['target'] = pd.Series(wine_dataset.target)
df_wine.head()


wine_dataset.data.shape

print(df_wine)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2

In [24]:
le = LabelEncoder()


X = df_wine.iloc[:, :-1].values

# Only last column, 0 for 1st column and -1 for last colum,-2 for 2nd last column
Y = df_wine.iloc[:, -1].values
print("\n\nInput : \n", X)
print("\n\nOutput: \n", Y)

features = wine_dataset.feature_names
# print(len(features))

# dataset[ : ,0] = le.fit_transform(dataset[ : ,0])

# i=1
i=0
while i < len(features):
    X[ : ,i] = le.fit_transform(X[ : ,i])
    i += 1
  



Input : 
 [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


Output: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [25]:
print("Features: ", wine_dataset.feature_names)
features = wine_dataset.feature_names;
print(features)
for i in features:
  dummy = pd.get_dummies(df_wine[i])
  df_wine = df_wine.drop([i],axis=1)
  df_wine = pd.concat([dummy,df_wine],axis=1)

print(df_wine)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
     278.0  290.0  312.0  315.0  325.0  342.0  345.0  352.0  355.0  365.0  \
0        0      0      0      0      0      0      0      0      0      0   
1        0      0      0      0      0      0      0      0      0      0   
2        0      0      0      0      0      0      0      0      0      0   
3        0      0      0      0      0      0      0      0      0      0   
4        0      0      0      0      0      0      0      0      0      0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
173      0      0      0      

In [26]:
target_dataset = pd.DataFrame(wine_dataset.data, columns=wine_dataset.feature_names)
features = wine_dataset.feature_names;
target_dataset['target'] = pd.Series(wine_dataset.target)
dummy = pd.get_dummies(target_dataset['target'])

for i in features:
  target_dataset = target_dataset.drop([i],axis=1)

target_dataset = target_dataset.drop(['target'],axis=1)
target_dataset = pd.concat([dummy, target_dataset], axis=1)

In [27]:
print(target_dataset)

     0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
173  0  0  1
174  0  0  1
175  0  0  1
176  0  0  1
177  0  0  1

[178 rows x 3 columns]


In [28]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(df_wine, Y, test_size = 0.20, random_state = 97)

print("\n\nInput : \n", data_train)
print("\n\nOutput: \n", target_train)

print("\n\nInput : \n", data_test)
print("\n\nOutput: \n", target_test)



Input : 
      278.0  290.0  312.0  315.0  325.0  342.0  345.0  352.0  355.0  365.0  \
25       0      0      0      0      0      0      0      0      0      0   
101      0      0      0      0      0      0      0      0      0      0   
54       0      0      0      0      0      0      0      0      0      0   
52       0      0      0      0      0      0      0      0      0      0   
60       0      0      0      0      0      0      0      0      0      0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
69       0      0      0      0      0      0      0      0      0      0   
28       0      0      0      0      0      0      0      0      0      0   
105      0      0      0      1      0      0      0      0      0      0   
163      0      0      0      0      0      0      0      0      0      0   
90       0      0      0      0      0      0      0      0      0      0   

     ...  14.22  14.23  14.3  14.34  14.37  14.38  14.39  14.75

In [29]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['float', 'str']. An error will be raised in 1.2.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['float', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [30]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics

print("Accuracy:" ,metrics.accuracy_score(target_test, target_pred))

precision = metrics.precision_score(target_test, target_pred, average=None)
recall = metrics.recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.9166666666666666
precision: [0.88235294 0.88888889 1.        ]
recall: [1.         0.8        0.90909091]


# **3_NB_Classifier_Iris_3Classes**

In [31]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

# print the names of the 13 features
print("Features: ", iris.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)

# print data(feature)shape
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [32]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data, iris.target, test_size = 0.30, random_state = 10)

In [33]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [34]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [35]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [36]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]
